Jusqu'ici nous avons manipulé des données avec des listes ou des dictionnaires

In [1]:
countryDict = {'France':70,'Angleterre':55,'Allemagne':85}
print(countryDict)

{'France': 70, 'Angleterre': 55, 'Allemagne': 85}


In [2]:
countryList = [['France',70],['Angleterre',55],['Allemagne',85]]
print(countryList)

[['France', 70], ['Angleterre', 55], ['Allemagne', 85]]


Pas adapté pour stoker des données pour une même dimension (pour un pays avoir la pop, le PIB, l'IDH))

<b> Créer un tableau </b>

In [3]:
import numpy as np
pays = np.array([
    ['France', 'Angleterre', 'Allemagne'], #Nom pays
    [70, 55, 85],                          #Population en millions
    [0.901, 0.922, 0.936],                 #IDH indice de developpement humain
    [2091,2077,3045]                       #PIB
])
print(pays)

[['France' 'Angleterre' 'Allemagne']
 ['70' '55' '85']
 ['0.901' '0.922' '0.936']
 ['2091' '2077' '3045']]


<b>Sélectionner des valeurs dans un tableau (slicing)</b>

In [7]:
pays[1]
pays[2]

array(['0.901', '0.922', '0.936'], dtype='<U32')

In [8]:
pays[1,1]

'55'

In [6]:
pays[:,1]

array(['Angleterre', '55', '0.922', '2077'], dtype='<U32')

In [9]:
pays[1:3,:]

array([['70', '55', '85'],
       ['0.901', '0.922', '0.936']], dtype='<U32')

In [10]:
pays[:,1:3]

array([['Angleterre', 'Allemagne'],
       ['55', '85'],
       ['0.922', '0.936'],
       ['2077', '3045']], dtype='<U32')

<b>Faire des opérations dans un tableau</b>

In [11]:
dataPays = pays[1:,:]
print(dataPays)
#dataPays[1,1] - 1  # ne fonctionne pas car data de type string


[['70' '55' '85']
 ['0.901' '0.922' '0.936']
 ['2091' '2077' '3045']]


In [12]:
dataPays = dataPays.astype(float)
dataPays

array([[7.000e+01, 5.500e+01, 8.500e+01],
       [9.010e-01, 9.220e-01, 9.360e-01],
       [2.091e+03, 2.077e+03, 3.045e+03]])

In [13]:
np.set_printoptions(suppress=True)
dataPays

array([[  70.   ,   55.   ,   85.   ],
       [   0.901,    0.922,    0.936],
       [2091.   , 2077.   , 3045.   ]])

In [ ]:
print(dataPays[1,1] - 1) # fonctionne maintenant
dataPays*2

In [14]:
pib2018 = np.array([2091,2077,3045])
pib2019 = np.array([2325,2101,3500])
pib20182019 = pib2018 + pib2019
pib20182019

array([4416, 4178, 6545])

<b>Analyser un tableau</b>

In [17]:
print(dataPays)
print ("dataPays.sum()")
print (dataPays.sum() )
print ("dataPays[2,:].sum()")
print( dataPays[2,:].sum()) #Sommes des PIB

[[  70.      55.      85.   ]
 [   0.901    0.922    0.936]
 [2091.    2077.    3045.   ]]
dataPays.sum()
7425.759
dataPays[2,:].sum()
7213.0


In [21]:
print(dataPays[2,:].min())
print(dataPays[2,:].max())
print(dataPays[2,:].mean()) #moyenne

2077.0
3045.0
2404.3333333333335


In [ ]:
bestPibIndex = dataPays[2,:].argmax()
worstPibIndex = dataPays[2,:].argmin()
print(bestPibIndex,worstPibIndex)

In [ ]:
print('le pays le plus riche : '+pays[0,bestPibIndex])
print('le pays le moins riche : '+pays[0,worstPibIndex])

In [ ]:
tab1 = np.array([1,2,3,4])
tab2 = np.array([1,7,3,4])
np.equal(tab1, tab2)

<b> Manipuler un tableau </b>

In [ ]:
dataPays[1,1] = 0
dataPays

In [20]:
np.concatenate((pib2018, pib2019), axis=0)

array([2091, 2077, 3045, 2325, 2101, 3500])

In [ ]:
dataPays = np.array([
    [1, np.nan, 3],
    [1, 2, 3],
    [1, 2, 3]
])
print(dataPays)

In [ ]:
dataPays*2

In [ ]:
np.nan_to_num(dataPays)

In [ ]:
Pays1 = np.array([
    [1, 2],
    [3, 4],
])
Pays2 = np.array([
    [5, 6],
    [7, 8],
])

print(Pays1*Pays2)
print(Pays1+Pays2)

#numpy peut également être utilisé pour du calcul matriciel (numpy.dot, array.T)

<b>Le module arrange<b>

In [ ]:
np.arange(1, 100, 2)

In [ ]:
np.arange(0, 1, 0.1)

In [ ]:
np.linspace(0, 100, 11)